<?php if (DEBUG): ?>
<script src="views/app/js/jdev.js"></script>
<?php else: ?>
    <script src="views/backend/js/jquery.js"></script>
<?php endif ?>

<!-- Placed js at the end of the document so the pages load faster -->
<!--Core js-->
<script src="views/backend/bs3/js/bootstrap.min.js"></script>
<script class="include" type="text/javascript" src="views/backend/js/jquery.dcjqaccordion.2.7.js"></script>
<script src="views/backend/js/jquery.scrollTo.min.js"></script>
<script src="views/backend/js/jQuery-slimScroll-1.3.0/jquery.slimscroll.js"></script>
<script src="views/backend/js/jquery.nicescroll.js"></script>
<!--Easy Pie Chart-->
<script src="views/backend/js/easypiechart/jquery.easypiechart.js"></script>
<!--Sparkline Chart-->
<script src="views/backend/js/sparkline/jquery.sparkline.js"></script>
<!--jQuery Flot Chart-->
<script src="views/backend/js/flot-chart/jquery.flot.js"></script>
<script src="views/backend/js/flot-chart/jquery.flot.tooltip.min.js"></script>
<script src="views/backend/js/flot-chart/jquery.flot.resize.js"></script>
<script src="views/backend/js/flot-chart/jquery.flot.pie.resize.js"></script>
<!--common script init for all pages-->
<script src="views/backend/js/scripts.js"></script>
<script src="views/app/js/jquery.numeric.js"></script>
<script>
  $('.numeric').numeric();
</script>
