<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="application-name" content="Ocrend Framework" />
    <meta name="author" content="www.ocrend.com" />
    <base href="<?=  URL ?>" />
    <link rel="shortcut icon" href="views/backend/images/favicon.html">
    <title><?= APP ?></title>

    <!--Core CSS -->
    <link href="views/backend/bs3/css/bootstrap.min.css" rel="stylesheet">
    <link href="views/backend/css/bootstrap-reset.css" rel="stylesheet">
    <link href="views/backend/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="views/backend/css/style.css" rel="stylesheet">
    <link href="views/backend/css/style-responsive.css" rel="stylesheet" />

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="views/backend/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

