<?= $this->insert('overall/head') ?>
<body class="login-body">
<div class="container">
    <form class="form-signin" role="form" enctype="application/x-www-form-urlencoded" id="login_form">
        <h2 class="form-signin-heading">sign in now</h2>
        <div class="alert hide" id="ajax_login"></div>
        <div class="login-wrap">
            <div class="user-login-info">
                <input type="text" name="user" class="form-control" placeholder="User ID" autofocus>
                <input type="password" name="pass" class="form-control" placeholder="Password">
            </div>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
                <span class="pull-right">
                    <a data-toggle="modal" href="#myModal"> Forgot Password?</a>
                </span>
            </label>
            <button class="btn btn-lg btn-login btn-block" type="button" id="login" >Sign in</button>
            <div class="registration">
                Don't have an account yet?
                <a class="" href="registration.html">
                    Create an account
                </a>
            </div>
        </div>
    </form>
</div>
<script src="views/backend/js/jquery.js"></script>
<script src="views/backend/bs3/js/bootstrap.min.js"></script>
<script src="views/app/js/login.js"></script>
</body>
</html>
